include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_final_locals
    - prefer_is_not_empty
    - prefer_single_quotes
    - unnecessary_null_checks
    - prefer_const_literals_to_create_immutables
    - avoid_unnecessary_containers
    - prefer_const_declarations
    - use_key_in_widget_constructors
    - avoid_redundant_argument_values
    - avoid_returning_null_for_void
    - avoid_positional_boolean_parameters
    - sort_child_properties_last
    - prefer_typing_uninitialized_variables
    - prefer_final_parameters
    - omit_local_variable_types
    - avoid_renaming_method_parameters
    - avoid_catches_without_on_clauses
    - avoid_void_async
    - always_use_package_imports
    - always_declare_return_types
    - await_only_futures
    - unawaited_futures
    - sort_constructors_first

analyzer:
  errors:
    library_private_types_in_public_api: ignore
    avoid_catches_without_on_clauses: ignore
