name: breeze
description: "Breeze browser"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # flutter_accessibility_service: ^0.2.4
  flutter_launcher_icons: ^0.14.1
  flutter_inappwebview: ^6.1.5
  http: ^1.2.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  html: ^0.15.4
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon.png
    - .env
